services:
  mysql:
    image: mysql:8.0
    container_name: mysql_digital_esign
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - esign_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 20

  digital_esign:
    build: .
    container_name: digital_esign
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/digital_esign?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimezone=UTC
        SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
        SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
        SPRING_APPLICATION_NAME: digital-esign-app
    networks:
      - esign_network


volumes:
  mysql_data:

networks:
  esign_network:
    driver: bridge